### ISSUE TITLE
What is takes to make it support mp3 files?

### ISSUE THREAD

**Issue by DvirH** [kitop/json-waveform#1]
I'm not ruby programmer and I'm running it on windows.
Is it complicated?

It's working great with wav files!

**Comment by kitop** [comment]
Unfortunately, `ruby-audio` (used by this code) works with `libsdnfile` which [doesn't support MP3](http://www.mega-nerd.com/libsndfile/FAQ.html#Q020).

The way to do work with mp3s is to have a previous step converting the mp3 to wav.
More info on that here: https://github.com/benalavi/waveform#converting-mp3-to-wav
