### ISSUE TITLE
ERROR:  Error installing json-waveform ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by zeeshansh-sds** [kitop/json-waveform#4]
working fine with ubuntu but unable to install on red-hat/centos.
Building native extensions.  This could take a while...
ERROR:  Error installing json-waveform:
    ERROR: Failed to build gem native extension.

```
/opt/rubies/ruby-2.1.2/bin/ruby extconf.rb
```

checking for sndfile.h in /opt/local/include,/usr/local/include,C:/Program Files (x86)/Mega-Nerd/libsndfile/include,C:/Program Files/Mega-Nerd/libsndfile/include... no
checking for sf_open() in -lsndfile-1... no
checking for sf_open() in -lsndfile... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by kitop** [comment]
This is probably due to the `ruby-audio` dependency. See https://github.com/kitop/json-waveform#installation

**Comment by kitop** [comment]
@zeeshansh-sds any luck fixing it?

**Comment by zeeshansh-sds** [comment]
yes your are right it is due to libsndfile1-dev. I have install it manually as  wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.27.tar.gz.
