### ISSUE TITLE
Invalid multibyte char

### ISSUE THREAD

**Issue by dobrygin** [kitop/json-waveform#6]
I got error on mac os high sierra 10.13.2 (17C88):
``` sh
$ json-waveform -h
/usr/local/bin/json-waveform:23:in `load': /usr/local/lib/ruby/gems/1.9.1/gems/json-waveform-0.2.1/bin/json-waveform:11: invalid multibyte char (US-ASCII) (SyntaxError)
/usr/local/lib/ruby/gems/1.9.1/gems/json-waveform-0.2.1/bin/json-waveform:11: invalid multibyte char (US-ASCII)
/usr/local/lib/ruby/gems/1.9.1/gems/json-waveform-0.2.1/bin/json-waveform:11: syntax error, unexpected $end, expecting ')'
... width). The result may have ±10% of the samples requested....
...                               ^
	from /usr/local/bin/json-waveform:23:in `<main>' ```

**Comment by dobrygin** [comment]
Then deleted this from json-waveform

> ±

**Comment by kitop** [comment]
Looks like you're using Ruby 1.9. That could be the culprit. 
If so, any particular reason you're using that version? It's been EOL for over 3 years.
Can you try it on ruby 2.3+?

**Comment by dobrygin** [comment]
> Looks like you're using Ruby 1.9. That could be the culprit.
> If so, any particular reason you're using that version? It's been EOL for over 3 years.
> Can you try it on ruby 2.3+?

This is default version of Ruby on MacOs High Sierra. I do not use Ruby, so I didn’t guess that I just need to upgrade, thanks. :)
